with catalog(brand, model, vehicle_type) as (values
('Abarth','500','sedan'),('Abarth','595','sedan'),
('Alfa Romeo','Giulietta','sedan'),('Alfa Romeo','Giulia','sedan'),('Alfa Romeo','Stelvio','crossover'),
('Audi','A1','sedan'),('Audi','A5','sedan'),('Audi','A7','sedan'),('Audi','A8','sedan'),('Audi','Q2','crossover'),('Audi','Q4 e-tron','crossover'),('Audi','Q8','crossover'),('Audi','e-tron','crossover'),
('Bentley','Continental GT','sedan'),('Bentley','Bentayga','crossover'),
('BMW','1 Series','sedan'),('BMW','2 Series','sedan'),('BMW','4 Series','sedan'),('BMW','6 Series','sedan'),('BMW','7 Series','sedan'),('BMW','X2','crossover'),('BMW','X4','crossover'),('BMW','X6','crossover'),('BMW','X7','crossover'),('BMW','i3','sedan'),('BMW','i4','sedan'),('BMW','iX','crossover'),
('BYD','Dolphin','sedan'),('BYD','Seal','sedan'),('BYD','Atto 3','crossover'),('BYD','Song Plus','crossover'),('BYD','Seal U','crossover'),('BYD','Tang','crossover'),
('Cadillac','CTS','sedan'),('Cadillac','XT4','crossover'),('Cadillac','XT5','crossover'),('Cadillac','Escalade','crossover'),
('Chery','Tiggo 4','crossover'),('Chery','Tiggo 7','crossover'),('Chery','Tiggo 8','crossover'),('Chery','Arrizo 8','sedan'),
('Chevrolet','Aveo','sedan'),('Chevrolet','Cruze','sedan'),('Chevrolet','Malibu','sedan'),('Chevrolet','Captiva','crossover'),('Chevrolet','Trax','crossover'),('Chevrolet','Tahoe','crossover'),
('Chrysler','300C','sedan'),('Chrysler','Pacifica','van'),('Chrysler','Voyager','van'),
('Citroen','C3','sedan'),('Citroen','C4','sedan'),('Citroen','C4 Cactus','crossover'),('Citroen','C4 Picasso','van'),('Citroen','C5 Aircross','crossover'),('Citroen','Berlingo','van'),('Citroen','Jumpy','van'),('Citroen','SpaceTourer','van'),
('Cupra','Leon','sedan'),('Cupra','Formentor','crossover'),('Cupra','Born','sedan'),
('Dacia','Sandero','sedan'),('Dacia','Lodgy','van'),('Dacia','Dokker','van'),('Dacia','Spring','sedan'),
('Daewoo','Matiz','sedan'),('Daewoo','Lanos','sedan'),('Daewoo','Nubira','sedan'),
('Dodge','Caliber','sedan'),('Dodge','Charger','sedan'),('Dodge','Journey','crossover'),('Dodge','Durango','crossover'),
('DS','DS 3','sedan'),('DS','DS 4','sedan'),('DS','DS 7','crossover'),('DS','DS 9','sedan'),
('Fiat','500','sedan'),('Fiat','Panda','sedan'),('Fiat','Tipo','sedan'),('Fiat','Punto','sedan'),('Fiat','Doblo','van'),('Fiat','Freemont','crossover'),
('Ford','Fiesta','sedan'),('Ford','Focus','sedan'),('Ford','Fusion','sedan'),('Ford','Mondeo','sedan'),('Ford','Puma','crossover'),('Ford','EcoSport','crossover'),('Ford','Kuga','crossover'),('Ford','Edge','crossover'),('Ford','Galaxy','van'),('Ford','S-Max','van'),('Ford','Tourneo Connect','van'),('Ford','Transit Custom','van'),('Ford','Ranger','crossover'),
('Geely','Emgrand','sedan'),('Geely','Coolray','crossover'),('Geely','Atlas','crossover'),('Geely','Monjaro','crossover'),('Geely','Geometry C','crossover'),
('Genesis','G70','sedan'),('Genesis','G80','sedan'),('Genesis','GV70','crossover'),('Genesis','GV80','crossover'),
('Great Wall','Hover','crossover'),('Great Wall','Wingle','crossover'),('Great Wall','Poer','crossover'),
('Haval','Jolion','crossover'),('Haval','H6','crossover'),('Haval','Dargo','crossover'),
('Honda','Jazz','sedan'),('Honda','Civic','sedan'),('Honda','Accord','sedan'),('Honda','HR-V','crossover'),('Honda','CR-V','crossover'),('Honda','e:Ny1','crossover'),
('Hyundai','i10','sedan'),('Hyundai','i30','sedan'),('Hyundai','i40','sedan'),('Hyundai','Accent','sedan'),('Hyundai','Sonata','sedan'),('Hyundai','Venue','crossover'),('Hyundai','Palisade','crossover'),('Hyundai','IONIQ 5','crossover'),('Hyundai','IONIQ 6','sedan'),
('Infiniti','Q30','sedan'),('Infiniti','Q50','sedan'),('Infiniti','QX30','crossover'),('Infiniti','QX50','crossover'),('Infiniti','QX70','crossover'),
('Isuzu','D-Max','crossover'),('Isuzu','MU-X','crossover'),
('Jaguar','XE','sedan'),('Jaguar','XF','sedan'),('Jaguar','F-Pace','crossover'),('Jaguar','E-Pace','crossover'),('Jaguar','I-Pace','crossover'),
('Jeep','Renegade','crossover'),('Jeep','Compass','crossover'),('Jeep','Cherokee','crossover'),('Jeep','Grand Cherokee','crossover'),('Jeep','Wrangler','crossover'),
('Kia','Picanto','sedan'),('Kia','Rio','sedan'),('Kia','Cerato','sedan'),('Kia','Optima','sedan'),('Kia','K5','sedan'),('Kia','Stonic','crossover'),('Kia','Niro','crossover'),('Kia','Soul','crossover'),('Kia','Seltos','crossover'),('Kia','Carnival','van'),('Kia','EV6','crossover'),
('Lada','Granta','sedan'),('Lada','Vesta','sedan'),('Lada','Niva','crossover'),('Lada','Largus','van'),
('Lancia','Ypsilon','sedan'),('Lancia','Delta','sedan'),
('Land Rover','Freelander','crossover'),('Land Rover','Discovery Sport','crossover'),('Land Rover','Discovery','crossover'),('Land Rover','Range Rover Evoque','crossover'),('Land Rover','Range Rover Velar','crossover'),('Land Rover','Range Rover Sport','crossover'),('Land Rover','Range Rover','crossover'),
('Lexus','CT','sedan'),('Lexus','IS','sedan'),('Lexus','ES','sedan'),('Lexus','LS','sedan'),('Lexus','UX','crossover'),('Lexus','NX','crossover'),('Lexus','RX','crossover'),('Lexus','GX','crossover'),('Lexus','LX','crossover'),
('Lincoln','MKZ','sedan'),('Lincoln','MKC','crossover'),('Lincoln','Navigator','crossover'),
('Maserati','Ghibli','sedan'),('Maserati','Levante','crossover'),('Maserati','Grecale','crossover'),
('Mazda','2','sedan'),('Mazda','3','sedan'),('Mazda','6','sedan'),('Mazda','CX-3','crossover'),('Mazda','CX-30','crossover'),('Mazda','CX-5','crossover'),('Mazda','CX-60','crossover'),('Mazda','CX-9','crossover'),
('Mercedes-Benz','A-Class','sedan'),('Mercedes-Benz','B-Class','van'),('Mercedes-Benz','CLA','sedan'),('Mercedes-Benz','CLS','sedan'),('Mercedes-Benz','S-Class','sedan'),('Mercedes-Benz','GLA','crossover'),('Mercedes-Benz','GLB','crossover'),('Mercedes-Benz','GLS','crossover'),('Mercedes-Benz','G-Class','crossover'),('Mercedes-Benz','EQA','crossover'),('Mercedes-Benz','EQB','crossover'),('Mercedes-Benz','EQS','sedan'),('Mercedes-Benz','Citan','van'),('Mercedes-Benz','Vito','van'),('Mercedes-Benz','Sprinter','van'),
('MG','MG3','sedan'),('MG','MG4','sedan'),('MG','ZS','crossover'),('MG','HS','crossover'),('MG','Marvel R','crossover'),
('MINI','Hatch','sedan'),('MINI','Clubman','sedan'),('MINI','Countryman','crossover'),
('Mitsubishi','Colt','sedan'),('Mitsubishi','Lancer','sedan'),('Mitsubishi','ASX','crossover'),('Mitsubishi','Eclipse Cross','crossover'),('Mitsubishi','Outlander','crossover'),('Mitsubishi','Pajero','crossover'),('Mitsubishi','L200','crossover'),
('Nissan','Micra','sedan'),('Nissan','Note','sedan'),('Nissan','Leaf','sedan'),('Nissan','Juke','crossover'),('Nissan','Murano','crossover'),('Nissan','Pathfinder','crossover'),('Nissan','Navara','crossover'),('Nissan','Ariya','crossover'),
('Opel','Corsa','sedan'),('Opel','Astra','sedan'),('Opel','Insignia','sedan'),('Opel','Mokka','crossover'),('Opel','Crossland','crossover'),('Opel','Grandland','crossover'),('Opel','Meriva','van'),('Opel','Zafira','van'),('Opel','Combo','van'),('Opel','Vivaro','van'),
('Peugeot','208','sedan'),('Peugeot','308','sedan'),('Peugeot','508','sedan'),('Peugeot','2008','crossover'),('Peugeot','3008','crossover'),('Peugeot','5008','crossover'),('Peugeot','Partner','van'),('Peugeot','Rifter','van'),('Peugeot','Traveller','van'),('Peugeot','Expert','van'),
('Polestar','2','sedan'),('Polestar','3','crossover'),
('Porsche','Panamera','sedan'),('Porsche','Macan','crossover'),('Porsche','Cayenne','crossover'),('Porsche','Taycan','sedan'),
('Renault','Twingo','sedan'),('Renault','Laguna','sedan'),('Renault','Talisman','sedan'),('Renault','Scenic','van'),('Renault','Grand Scenic','van'),('Renault','Kadjar','crossover'),('Renault','Arkana','crossover'),('Renault','Koleos','crossover'),('Renault','Espace','van'),('Renault','Trafic','van'),('Renault','Master','van'),('Renault','Zoe','sedan'),
('Rover','25','sedan'),('Rover','45','sedan'),('Rover','75','sedan'),
('Saab','9-3','sedan'),('Saab','9-5','sedan'),
('SEAT','Ibiza','sedan'),('SEAT','Leon','sedan'),('SEAT','Toledo','sedan'),('SEAT','Arona','crossover'),('SEAT','Ateca','crossover'),('SEAT','Tarraco','crossover'),('SEAT','Alhambra','van'),
('Skoda','Rapid','sedan'),('Skoda','Scala','sedan'),('Skoda','Yeti','crossover'),('Skoda','Enyaq','crossover'),
('Smart','Fortwo','sedan'),('Smart','Forfour','sedan'),('Smart','#1','crossover'),
('SsangYong','Tivoli','crossover'),('SsangYong','Korando','crossover'),('SsangYong','Rexton','crossover'),
('Subaru','Impreza','sedan'),('Subaru','Legacy','sedan'),('Subaru','XV','crossover'),('Subaru','Crosstrek','crossover'),('Subaru','Forester','crossover'),('Subaru','Outback','crossover'),
('Suzuki','Swift','sedan'),('Suzuki','Baleno','sedan'),('Suzuki','Ignis','crossover'),('Suzuki','SX4','crossover'),('Suzuki','Vitara','crossover'),('Suzuki','S-Cross','crossover'),('Suzuki','Jimny','crossover'),
('Tesla','Model 3','sedan'),('Tesla','Model S','sedan'),('Tesla','Model Y','crossover'),('Tesla','Model X','crossover'),
('Toyota','Aygo','sedan'),('Toyota','Yaris','sedan'),('Toyota','Auris','sedan'),('Toyota','Avensis','sedan'),('Toyota','Prius','sedan'),('Toyota','C-HR','crossover'),('Toyota','Highlander','crossover'),('Toyota','Venza','crossover'),('Toyota','Sienna','van'),('Toyota','Hilux','crossover'),('Toyota','Proace','van'),('Toyota','Proace City','van'),
('Volkswagen','Polo','sedan'),('Volkswagen','Jetta','sedan'),('Volkswagen','Arteon','sedan'),('Volkswagen','Touran','van'),('Volkswagen','Sharan','van'),('Volkswagen','Transporter','van'),('Volkswagen','Crafter','van'),('Volkswagen','Amarok','crossover'),('Volkswagen','ID.3','sedan'),('Volkswagen','ID.4','crossover'),('Volkswagen','ID.5','crossover'),('Volkswagen','ID. Buzz','van'),
('Volvo','S40','sedan'),('Volvo','S60','sedan'),('Volvo','S90','sedan'),('Volvo','V40','sedan'),('Volvo','V60','sedan'),('Volvo','V90','sedan'),('Volvo','XC40','crossover'),('Volvo','XC60','crossover'),('Volvo','XC70','crossover'),('Volvo','XC90','crossover'),('Volvo','EX30','crossover'),
('Zeekr','001','sedan'),('Zeekr','X','crossover'),('Zeekr','7X','crossover'),
('ZAZ','Chance','sedan'),('ZAZ','Forza','sedan'),('ZAZ','Sens','sedan')
)
insert into public.vehicle_models (brand, model, vehicle_type, express_price, complex_price, detailing_price, active, sort_order)
select brand, model, vehicle_type,
  case vehicle_type when 'sedan' then 350 when 'crossover' then 450 else 550 end,
  case vehicle_type when 'sedan' then 790 when 'crossover' then 950 else 1150 end,
  case vehicle_type when 'sedan' then 2900 when 'crossover' then 3500 else 4200 end,
  true,
  200 + row_number() over (order by brand, model)
from catalog
on conflict (brand, model) do nothing;
