create table public.vehicle_models (
  id bigint generated by default as identity primary key,
  brand text not null check (char_length(btrim(brand)) between 1 and 60),
  model text not null check (char_length(btrim(model)) between 1 and 80),
  vehicle_type text not null check (vehicle_type in ('sedan', 'crossover', 'van')),
  express_price numeric(10,2) not null check (express_price >= 0),
  complex_price numeric(10,2) not null check (complex_price >= 0),
  detailing_price numeric(10,2) not null check (detailing_price >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand, model)
);

alter table public.vehicle_models enable row level security;
revoke all on table public.vehicle_models from anon, authenticated;
grant select on table public.vehicle_models to anon, authenticated;
grant insert (brand, model, vehicle_type, express_price, complex_price, detailing_price, active, sort_order) on table public.vehicle_models to authenticated;
grant update (brand, model, vehicle_type, express_price, complex_price, detailing_price, active, sort_order, updated_at) on table public.vehicle_models to authenticated;
grant delete on table public.vehicle_models to authenticated;
grant usage, select on sequence public.vehicle_models_id_seq to authenticated;

create policy "public can view active vehicle models"
on public.vehicle_models for select
using (active or exists (
  select 1 from public.staff_users s
  where s.id = (select auth.uid()) and s.active and s.role = 'owner'
));

create policy "owners can add vehicle models"
on public.vehicle_models for insert to authenticated
with check (exists (
  select 1 from public.staff_users s
  where s.id = (select auth.uid()) and s.active and s.role = 'owner'
));

create policy "owners can update vehicle models"
on public.vehicle_models for update to authenticated
using (exists (
  select 1 from public.staff_users s
  where s.id = (select auth.uid()) and s.active and s.role = 'owner'
))
with check (exists (
  select 1 from public.staff_users s
  where s.id = (select auth.uid()) and s.active and s.role = 'owner'
));

create policy "owners can delete vehicle models"
on public.vehicle_models for delete to authenticated
using (exists (
  select 1 from public.staff_users s
  where s.id = (select auth.uid()) and s.active and s.role = 'owner'
));

insert into public.vehicle_models (brand, model, vehicle_type, express_price, complex_price, detailing_price, sort_order) values
('Audi','A3','sedan',350,790,2900,10),('Audi','A4','sedan',350,790,2900,11),('Audi','A6','sedan',350,790,2900,12),('Audi','Q3','crossover',450,950,3500,13),('Audi','Q5','crossover',450,950,3500,14),('Audi','Q7','crossover',450,950,3500,15),
('BMW','3 Series','sedan',350,790,2900,20),('BMW','5 Series','sedan',350,790,2900,21),('BMW','X1','crossover',450,950,3500,22),('BMW','X3','crossover',450,950,3500,23),('BMW','X5','crossover',450,950,3500,24),
('Dacia','Logan','sedan',350,790,2900,30),('Dacia','Sandero Stepway','crossover',450,950,3500,31),('Dacia','Duster','crossover',450,950,3500,32),('Dacia','Jogger','van',550,1150,4200,33),('Dacia','Bigster','crossover',450,950,3500,34),
('Hyundai','i20','sedan',350,790,2900,40),('Hyundai','Elantra','sedan',350,790,2900,41),('Hyundai','Bayon','crossover',450,950,3500,42),('Hyundai','Kona','crossover',450,950,3500,43),('Hyundai','Tucson','crossover',450,950,3500,44),('Hyundai','Santa Fe','crossover',450,950,3500,45),('Hyundai','Staria','van',550,1150,4200,46),
('Kia','Ceed','sedan',350,790,2900,50),('Kia','Sportage','crossover',450,950,3500,51),('Kia','Sorento','crossover',450,950,3500,52),
('Mercedes-Benz','C-Class','sedan',350,790,2900,60),('Mercedes-Benz','E-Class','sedan',350,790,2900,61),('Mercedes-Benz','GLC','crossover',450,950,3500,62),('Mercedes-Benz','GLE','crossover',450,950,3500,63),('Mercedes-Benz','V-Class','van',550,1150,4200,64),
('Nissan','Qashqai','crossover',450,950,3500,70),('Nissan','X-Trail','crossover',450,950,3500,71),
('Renault','Clio','sedan',350,790,2900,80),('Renault','Megane','sedan',350,790,2900,81),('Renault','Captur','crossover',450,950,3500,82),('Renault','Austral','crossover',450,950,3500,83),('Renault','Kangoo','van',550,1150,4200,84),
('Skoda','Fabia','sedan',350,790,2900,90),('Skoda','Octavia','sedan',350,790,2900,91),('Skoda','Superb','sedan',350,790,2900,92),('Skoda','Kamiq','crossover',450,950,3500,93),('Skoda','Karoq','crossover',450,950,3500,94),('Skoda','Kodiaq','crossover',450,950,3500,95),
('Toyota','Yaris Cross','crossover',450,950,3500,100),('Toyota','Corolla Sedan','sedan',350,790,2900,101),('Toyota','Corolla Cross','crossover',450,950,3500,102),('Toyota','Camry','sedan',350,790,2900,103),('Toyota','RAV4','crossover',450,950,3500,104),('Toyota','Land Cruiser Prado','crossover',450,950,3500,105),('Toyota','Land Cruiser 300','crossover',450,950,3500,106),('Toyota','Proace City Verso','van',550,1150,4200,107),
('Volkswagen','Golf','sedan',350,790,2900,110),('Volkswagen','Passat','sedan',350,790,2900,111),('Volkswagen','T-Roc','crossover',450,950,3500,112),('Volkswagen','Tiguan','crossover',450,950,3500,113),('Volkswagen','Touareg','crossover',450,950,3500,114),('Volkswagen','Caddy','van',550,1150,4200,115),('Volkswagen','Multivan','van',550,1150,4200,116);

create or replace function private.booking_vehicle_price(service_id text, car_name text, vehicle_id text)
returns numeric
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select case service_id
      when 'express' then v.express_price
      when 'complex' then v.complex_price
      when 'detailing' then v.detailing_price
      else null end
     from public.vehicle_models v
     where lower(v.brand || ' ' || v.model) = lower(btrim(car_name)) and v.active
     limit 1),
    private.booking_service_price(service_id, vehicle_id),
    0
  );
$$;

revoke all on function private.booking_vehicle_price(text, text, text) from public;

create or replace function private.enforce_booking_capacity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  settings_row public.site_settings%rowtype;
  proposed_start timestamp;
  proposed_end timestamp;
  local_now timestamp := timezone('Europe/Chisinau', now());
  free_bay integer;
begin
  if new.status not in ('new', 'confirmed') then return new; end if;
  select * into settings_row from public.site_settings where id = 1;
  new.duration_minutes := coalesce(nullif(new.duration_minutes, 90), private.booking_service_duration(new.service), 90);
  if tg_op = 'INSERT' or new.price_amount = 0 then
    new.duration_minutes := coalesce(private.booking_service_duration(new.service), new.duration_minutes);
    new.price_amount := coalesce(private.booking_vehicle_price(new.service, new.car, new.vehicle_type), 0);
  end if;
  if new.booking_date < local_now::date or new.booking_date > local_now::date + 90 then raise exception 'booking_date_out_of_range' using errcode = '22007'; end if;
  proposed_start := new.booking_date + new.booking_time;
  proposed_end := proposed_start + make_interval(mins => new.duration_minutes);
  if proposed_start <= local_now then raise exception 'booking_time_has_passed' using errcode = '22007'; end if;
  if new.booking_time < settings_row.opening_time or proposed_end > new.booking_date + settings_row.closing_time then raise exception 'outside_working_hours' using errcode = '22007'; end if;
  if exists (select 1 from public.business_closures c where c.closure_date = new.booking_date and (c.start_time is null or (proposed_start < c.closure_date + c.end_time and proposed_end > c.closure_date + c.start_time))) then raise exception 'business_closed' using errcode = '22007'; end if;
  perform pg_advisory_xact_lock(hashtext(new.booking_date::text));
  select bay into free_bay from generate_series(1, settings_row.bay_count) bay
  where not exists (select 1 from public.bookings b where b.id is distinct from new.id and b.status in ('new','confirmed') and b.booking_date = new.booking_date and b.bay_number = bay and proposed_start < b.booking_date + b.booking_time + make_interval(mins => b.duration_minutes) and proposed_end > b.booking_date + b.booking_time)
  order by bay limit 1;
  if free_bay is null then raise exception 'slot_capacity_reached' using errcode = '23505'; end if;
  new.bay_number := free_bay;
  return new;
end;
$$;

revoke all on function private.enforce_booking_capacity() from public;
